
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftMainActivityBinding$Responder ///

public protocol SwiftMainActivityBinding_Responder: JavaProtocol {

}


open class SwiftMainActivityBinding_ResponderForward: JNIObjectForward, SwiftMainActivityBinding_Responder {

    private static var SwiftMainActivityBinding_ResponderJNIClass: jclass?

}

