
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftMainActivityBinding ///

public protocol SwiftMainActivityBinding: JavaProtocol {

}


open class SwiftMainActivityBindingForward: JNIObjectForward, SwiftMainActivityBinding {

    private static var SwiftMainActivityBindingJNIClass: jclass?

}

