
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftBluetoothScannerActivityBinding$Responder ///

public protocol SwiftBluetoothScannerActivityBinding_Responder: SwiftMainActivityBinding_Responder {

    /// public abstract java.lang.Object com.johnholdsworth.swiftbindings.SwiftBluetoothScannerActivityBinding$Responder.getLayoutInflater()

    func getLayoutInflater() -> java_swift.JavaObject!

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothScannerActivityBinding$Responder.setAdapter(java.lang.Object)

    func setAdapter( adapter: java_swift.JavaObject? )

}


open class SwiftBluetoothScannerActivityBinding_ResponderForward: SwiftMainActivityBinding_ResponderForward, SwiftBluetoothScannerActivityBinding_Responder {

    private static var SwiftBluetoothScannerActivityBinding_ResponderJNIClass: jclass?

    /// public abstract java.lang.Object com.johnholdsworth.swiftbindings.SwiftBluetoothScannerActivityBinding$Responder.getLayoutInflater()

    private static var getLayoutInflater_MethodID_3: jmethodID?

    open func getLayoutInflater() -> java_swift.JavaObject! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getLayoutInflater", methodSig: "()Ljava/lang/Object;", methodCache: &SwiftBluetoothScannerActivityBinding_ResponderForward.getLayoutInflater_MethodID_3, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaObject( javaObject: __return ) : nil
    }


    /// public abstract void com.johnholdsworth.swiftbindings.SwiftBluetoothScannerActivityBinding$Responder.setAdapter(java.lang.Object)

    private static var setAdapter_MethodID_4: jmethodID?

    open func setAdapter( adapter: java_swift.JavaObject? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: adapter, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setAdapter", methodSig: "(Ljava/lang/Object;)V", methodCache: &SwiftBluetoothScannerActivityBinding_ResponderForward.setAdapter_MethodID_4, args: &__args, locals: &__locals )
    }

    open func setAdapter( _ _adapter: java_swift.JavaObject? ) {
        setAdapter( adapter: _adapter )
    }

}

